spring:
  application:
    name: mark-api

server:
  port: 8080
  servlet:
    context-path: /api

mark-service:
  ribbon:
    listOfServers: http://127.0.0.1:9003

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 50000



feign:
  hystrix:
    enabled: true
#  compression:
#    request.enabled: true
#    response:enabled: true


ribbon:
  eureka:
    enabled: false

logging:
  level:
    com.yong.gateway.client: DEBUG
